### PR TITLE
Make Eddie Tor Bridge-Aware (at least on Windows)

### PR DESCRIPTION
**Pull request by x0wllaar**
@Clodo76 
I've used the method described in [this forum post](https://airvpn.org/topic/21340-airvpn-tor-obfs4-bridges/#entry61200). 

On windows, this code seems to work fine, but I didn't test it on Linux or macOS, so yeah...

### CODE REVIEW

**Comment by baimafeima** [comment]
I hope this works on Linux-based systems too. Will test this once it is accepted.

**Comment by x0wllaar** [comment]
@baimafeima @Clodo76 
So, I've tested it in a Linux VM and it worked (screenshot [attached](https://i.imgur.com/5idNmQQ.jpg))

Since this repo is not very active, you can git clone my fork of Eddie and build it as described [here](https://airvpn.org/topic/12760-how-can-i-compile-the-source-code/) (install mono-complete using instructions from [here](http://www.mono-project.com/download/#download-lin))

**Comment by Clodo76** [comment]
Sorry for the delay. Thanks for the pull.
I will reject this pull (for conflict issues) and apply manually your changes to the main code.
I hope it will available in the next release. Please be patience. Thanks again.

**Comment by baimafeima** [comment]
@Clodo76 I assume this will also work with Linux-based operating systems?

**Comment by Clodo76** [comment]
The latest 2.14.0 in beta forum : https://airvpn.org/topic/25149-eddie-214beta-released/
implement this. 
https://eddie.website/changelog/?software=client&format=html
`[new] Detection of Tor Guard IP in bridge configuration (Thanks to https://github.com/x0wllaar)`

I'm sorry but due to an internal re-organization, we can update the official repository here only when the 2.14 reach the stable release.

**Pull request closed without merging**
